# Generated by Django 3.2.5 on 2024-10-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alunomateria',
            unique_together={('aluno', 'materia')},
        ),
    ]
